/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "FaustVerb.h"

// Include compiled network files ------------------

#include "chorus.h"
#include "Compressor.h"
#include "crusher.h"
#include "delay.h"
#include "FaustReverb.h"
#include "Tremolo.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

